package com.aaron.sidegesture.ktx

import android.content.Context
import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.aaron.sidegesture.R
import com.aaron.sidegesture.constant.GlobalActions

/**
 * @author aaronzzxup@gmail.com
 * @since 2024/11/29
 */

fun Context.actionText(action: String, emptyIfNone: Boolean = true): String = when (action) {
    GlobalActions.BACK -> getString(R.string.action_back)
    GlobalActions.HOME -> getString(R.string.action_home)
    GlobalActions.RECENT -> getString(R.string.action_recent)
    GlobalActions.MENU -> getString(R.string.action_menu)
    GlobalActions.SEARCH_IN_APP -> getString(R.string.action_search_in_app)
    GlobalActions.VOLUME_UP -> getString(R.string.action_volume_up)
    GlobalActions.VOLUME_DOWN -> getString(R.string.action_volume_down)
    GlobalActions.MUTE -> getString(R.string.action_mute)
    GlobalActions.PLAY_PAUSE_SONG -> getString(R.string.action_play_pause_song)
    GlobalActions.LAST_SONG -> getString(R.string.action_last_song)
    GlobalActions.NEXT_SONG -> getString(R.string.action_next_song)
    GlobalActions.PREVIOUS_APP -> getString(R.string.action_previous_app)
    GlobalActions.APP_SCREEN -> getString(R.string.action_app_screen)
    GlobalActions.WEB_FORWARD -> getString(R.string.action_web_forward)
    GlobalActions.OPEN_NOTIFICATION_PANEL -> getString(R.string.action_open_notification_panel)
    GlobalActions.OPEN_QUICK_PANEL -> getString(R.string.action_open_quick_panel)
    GlobalActions.LOCK_SCREEN -> getString(R.string.action_lock_screen)
    GlobalActions.KILL_APP -> getString(R.string.action_kill_app)
    GlobalActions.FLASHLIGHT -> getString(R.string.action_flashlight)
    GlobalActions.SPLIT_SCREEN -> getString(R.string.action_split_screen)
    GlobalActions.POPUP_SCREEN -> getString(R.string.action_popup_screen)
    GlobalActions.ASSIST_APP -> getString(R.string.action_assist_app)
    GlobalActions.SEARCH -> getString(R.string.action_search)
    GlobalActions.SCREENSHOT -> getString(R.string.action_screenshot)
    GlobalActions.RECORD_SCREEN -> getString(R.string.action_record_screen)
    GlobalActions.SHOW_HIDE_NAV_BAR -> getString(R.string.action_show_hide_nav_bar)
    GlobalActions.PULL_SCREEN_DOWN -> getString(R.string.action_pull_screen_down)
    GlobalActions.EASY_ONE_HAND -> getString(R.string.action_easy_one_hand)
    GlobalActions.POWER_BUTTON -> getString(R.string.action_power_button)
    GlobalActions.AUTO_ROTATE -> getString(R.string.action_auto_rotate)
    GlobalActions.ROTATE_RIGHT -> getString(R.string.action_rotate_right)
    GlobalActions.ROTATE_LEFT -> getString(R.string.action_rotate_left)
    GlobalActions.INVERSE_COLOR -> getString(R.string.action_inverse_color)
    GlobalActions.QUICK_APP_PANEL -> getString(R.string.action_quick_app_panel)
    GlobalActions.LAUNCH_APP -> getString(R.string.action_launch_app)
    GlobalActions.LAUNCH_APP_IN_POPUP -> getString(R.string.action_launch_app_in_popup)
    GlobalActions.TASK_SWITCHER -> getString(R.string.action_task_switcher)
    GlobalActions.QUICK_TOOLS -> getString(R.string.action_quick_tools)
    GlobalActions.FLOAT_BALL-> getString(R.string.action_float_ball)
    GlobalActions.HIDE_GESTURE_BUTTON -> getString(R.string.action_hide_gesture_button)
    GlobalActions.WECHAT_SCAN -> getString(R.string.action_wechat_scan)
    GlobalActions.WECHAT_PAY -> getString(R.string.action_wechat_pay_simulate_click)
    GlobalActions.ALIPAY_SCAN -> getString(R.string.action_alipay_scan)
    GlobalActions.ALIPAY_PAY -> getString(R.string.action_alipay_pay)
    else -> if (emptyIfNone) "" else getString(R.string.action_none)
}

@Composable
fun actionText(action: String, emptyIfNone: Boolean = true): String = when (action) {
    GlobalActions.BACK -> stringResource(R.string.action_back)
    GlobalActions.HOME -> stringResource(R.string.action_home)
    GlobalActions.RECENT -> stringResource(R.string.action_recent)
    GlobalActions.MENU -> stringResource(R.string.action_menu)
    GlobalActions.SEARCH_IN_APP -> stringResource(R.string.action_search_in_app)
    GlobalActions.VOLUME_UP -> stringResource(R.string.action_volume_up)
    GlobalActions.VOLUME_DOWN -> stringResource(R.string.action_volume_down)
    GlobalActions.MUTE -> stringResource(R.string.action_mute)
    GlobalActions.PLAY_PAUSE_SONG -> stringResource(R.string.action_play_pause_song)
    GlobalActions.LAST_SONG -> stringResource(R.string.action_last_song)
    GlobalActions.NEXT_SONG -> stringResource(R.string.action_next_song)
    GlobalActions.PREVIOUS_APP -> stringResource(R.string.action_previous_app)
    GlobalActions.APP_SCREEN -> stringResource(R.string.action_app_screen)
    GlobalActions.WEB_FORWARD -> stringResource(R.string.action_web_forward)
    GlobalActions.OPEN_NOTIFICATION_PANEL -> stringResource(R.string.action_open_notification_panel)
    GlobalActions.OPEN_QUICK_PANEL -> stringResource(R.string.action_open_quick_panel)
    GlobalActions.LOCK_SCREEN -> stringResource(R.string.action_lock_screen)
    GlobalActions.KILL_APP -> stringResource(R.string.action_kill_app)
    GlobalActions.FLASHLIGHT -> stringResource(R.string.action_flashlight)
    GlobalActions.SPLIT_SCREEN -> stringResource(R.string.action_split_screen)
    GlobalActions.POPUP_SCREEN -> stringResource(R.string.action_popup_screen)
    GlobalActions.ASSIST_APP -> stringResource(R.string.action_assist_app)
    GlobalActions.SEARCH -> stringResource(R.string.action_search)
    GlobalActions.SCREENSHOT -> stringResource(R.string.action_screenshot)
    GlobalActions.RECORD_SCREEN -> stringResource(R.string.action_record_screen)
    GlobalActions.SHOW_HIDE_NAV_BAR -> stringResource(R.string.action_show_hide_nav_bar)
    GlobalActions.PULL_SCREEN_DOWN -> stringResource(R.string.action_pull_screen_down)
    GlobalActions.EASY_ONE_HAND -> stringResource(R.string.action_easy_one_hand)
    GlobalActions.POWER_BUTTON -> stringResource(R.string.action_power_button)
    GlobalActions.AUTO_ROTATE -> stringResource(R.string.action_auto_rotate)
    GlobalActions.ROTATE_RIGHT -> stringResource(R.string.action_rotate_right)
    GlobalActions.ROTATE_LEFT -> stringResource(R.string.action_rotate_left)
    GlobalActions.INVERSE_COLOR -> stringResource(R.string.action_inverse_color)
    GlobalActions.QUICK_APP_PANEL -> stringResource(R.string.action_quick_app_panel)
    GlobalActions.LAUNCH_APP -> stringResource(R.string.action_launch_app)
    GlobalActions.LAUNCH_APP_IN_POPUP -> stringResource(R.string.action_launch_app_in_popup)
    GlobalActions.TASK_SWITCHER -> stringResource(R.string.action_task_switcher)
    GlobalActions.QUICK_TOOLS -> stringResource(R.string.action_quick_tools)
    GlobalActions.FLOAT_BALL-> stringResource(R.string.action_float_ball)
    GlobalActions.HIDE_GESTURE_BUTTON -> stringResource(R.string.action_hide_gesture_button)
    GlobalActions.WECHAT_SCAN -> stringResource(R.string.action_wechat_scan)
    GlobalActions.WECHAT_PAY -> stringResource(R.string.action_wechat_pay_simulate_click)
    GlobalActions.ALIPAY_SCAN -> stringResource(R.string.action_alipay_scan)
    GlobalActions.ALIPAY_PAY -> stringResource(R.string.action_alipay_pay)
    else -> if (emptyIfNone) "" else stringResource(R.string.action_none)
}